### PR TITLE
Update synonyms.txt

### PR DESCRIPTION
**Pull request by petacat**

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Hm, so is it correct to say that "Kleiner Sommerweg" should always be rewritten as "Kleine Sommerweg"? That's what this effectively does.

What I had before was, ignoring grammar, "Kl" could be "Kleine", "Kleiner" or "Kleines", so when expand_address sees "Kl" in German it will produce all three versions, and one of them will be the correct one.

**Comment by petacat** [comment]
I was wrong. I didn't know that the lines are piped right to left. I thought all left ones are replaced with the right most.

**Comment by thatdatabaseguy** [comment]
Ah ok, no worries. Thanks for the updates!

**Comment by petacat** [comment]
Your welcome.

By the way: "Kleine", "Kleiner" and "Kleines" are the same word but for she/he/it.

**Pull request closed without merging**
