### PR TITLE
cstring_array_from_char_array returns NULL for empty char array

### PR DESCRIPTION
**Pull request by rinigus**
When using geodb for a country without postal codes, I stumbled on a case where a call to cstring_array_from_char_array with an empty str led to core dump (str->n==0). This patch fixes an issue.

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Fixed in a different way with https://github.com/openvenues/libpostal/commit/e1f258171fb4a6d415d40241be00d7eda43f6110 (shouldn't return NULL if the input is an empty char_array, can just return an empty cstring_array).

**Comment by rinigus** [comment]
Tried that before suggesting the fix in PR. At first, I also added `if (str->n > 0)` at the same place, as you did. Unfortunately, that resulted in a different crash:

```
#0  sparkey_hash_close (reader_ref=reader_ref@entry=0x2330340) at hashreader.c:105
105	  if (reader->open_status != MAGIC_VALUE_HASHREADER) {
(gdb) backtrace 
#0  sparkey_hash_close (reader_ref=reader_ref@entry=0x2330340) at hashreader.c:105
#1  0x00007ff42956021b in geodb_destroy (self=0x2330320) at geodb.c:25
#2  0x00007ff429560610 in geodb_init (dir=dir@entry=0x61ceb0 "postal-data/EE/geodb") at geodb.c:155
#3  0x00007ff429560669 in geodb_load (dir=dir@entry=0x61ceb0 "postal-data/EE/geodb") at geodb.c:160
#4  0x00007ff429560933 in geodb_module_setup (dir=dir@entry=0x61ceb0 "postal-data/EE/geodb") at geodb.c:233
#5  0x00007ff429543bba in libpostal_setup_parser_datadir (datadir=0x4117f7 "postal-data/EE") at libpostal.c:1134
```

**Comment by thatdatabaseguy** [comment]
Hm, so I think it's better to fix the actual cause of that crash (probably some assumption that the saved array length is non-zero) than to change the expected behavior of a util function that may be used elsewhere. Also not sure if it's a great idea to have geodb->postal_codes be NULL in case it gets used somewhere in the future. Usually prefer to have pointers be non-NULL after initialization unless NULL has a specific meaning.

Guessing the problem would be this line: https://github.com/openvenues/libpostal/blob/master/src/geodb.c#L93. When postal_code_str_len is 0, that would translate into a call to char_array_new_size(0) which in turn would end up calling malloc(0), which is implementation-defined in C99 and can return NULL on some systems, thus causing char_array_new_size to return NULL and the whole initialization to fail.

The change in https://github.com/openvenues/libpostal/commit/1398df1260ed9d6a76c2c097e8d41223e58a2f5e guarantees that any call to *_array_new_size(0) will malloc at least 1 byte. Try pulling latest and running it again.

Also added a change in https://github.com/openvenues/libpostal/commit/df89387b5c6472335df9ce387de15f5f1b65af20 that should make crashes like that more graceful. That sparkey error is not very indicative of what's going on. When initialization of certain structs fails, libpostal will abort and use their destructors to clean up, where said destructors are all just written to check for NULL member pointers before deallocating them. However, most of the time the initial structs were allocated with ```malloc```, so some of the member pointers would be uninitialized garbage memory if initialization failed early, causing crashes during cleanup. The latest change use ```calloc``` for such cases so the memory for the parent struct is zeroed out and thus the member pointers will be set to NULL before any of the subsequent initialization.

**Comment by rinigus** [comment]
Agreed, utilities have to be modified very carefully. 

However, the latest version still breaks on zero postcodes. Namely, it fails on https://github.com/openvenues/libpostal/blob/master/src/geodb.c#L103 since with the latest version of `cstring_array_from_char_array` the index returned by `cstring_array_num_strings` is `one` for the case where number of postal codes (str->n) was `zero`. 

The version below fixes the issue somewhat differently:

```
cstring_array *cstring_array_from_char_array(char_array *str) {
    if (str == NULL) return NULL;
    if (str->n == 0)
        return cstring_array_new();

    cstring_array *array = malloc(sizeof(cstring_array));
    if (array == NULL) return NULL;
    
    array->str = str;
    array->indices = uint32_array_new_size(1);
    
    uint32_array_push(array->indices, 0);
    char *ptr = str->a;
    for (uint32_t i = 0; i < str->n - 1; i++, ptr++) {
        if (*ptr == '\0') {
            uint32_array_push(array->indices, i + 1);
        }
    }
    return array;
}
```

Corresponding PR is submitted below or you could test and review it from the code above.

**Comment by thatdatabaseguy** [comment]
Ah ok, thought num_strings was returning indices->n - 1 but the special cases of length zero and length one are handled elsewhere. That should be fine to merge.

**Pull request merged**
