### PR TITLE
expansion of malay dictionary

### PR DESCRIPTION
**Pull request by Jeffrey04**
most of this are for malaysian address

### CODE REVIEW

**Comment by thatdatabaseguy** [comment]
Three issues:

1. The filename should be ```ambiguous_expansions.txt``` with an "s". The build validates any new dictionary files that are added to make sure the filenames are correct, hence why it's failing.

2. The ambiguous_expansions.txt file may not actually be needed. The purpose of the ambiguous_expansions dictionary is for tokens that _shouldn't_ always be expanded. For instance, almost all single letter abbreviations can also be initials in someone's name or just the plain letter. "E" is usually an abbreviation for "East" in English, but there's also an "[Avenue E](https://en.wikipedia.org/wiki/List_of_lettered_Brooklyn_avenues#Avenue_E)" in Brooklyn, which should not expand to "Avenue East". Something like "sek" only needs to be included in this dictionary if "sek" is also a valid Malay word on its own and shouldn't be expanded to "sekola", which doesn't appear to be the case.

3. English words shouldn't be on the same line as Malay words, e.g.

```
building| bangunan|bgn
```

The way you have it here, any time libpostal sees  "bgn" or "bangunan" in a Malay address, expand_address will replace it with "building", which feels wrong if the original input was written in pure Malay.

One option would be to split it into:

```
building|bldg
bangunan|bgn
```

Though, on looking at this further, I think only actual Malay words should appear in this dictionary. We can still use English dictionaries in Malaysia by making English an "unofficial language." Generally that approach should be preferable to duplicating terms across dictionaries, keeping them up-to-date, etc.

**Comment by Jeffrey04** [comment]
ok (:

**Comment by Jeffrey04** [comment]
pull request is updated, sorry for the delay

**Comment by thatdatabaseguy** [comment]
There are still a few more issues.

Lines like this:

```
flat|pangsapuri|rumah pangsa|p/puri
```

The word "flat" is still English should be removed and the other terms should be separated into distinct sets of abbreviations:

```
pangsapuri|p / puri
rumah pangsa
```

There are terms in personal_titles.txt that have English canonical forms like:

```
mr|encik|en
mrs|puan|pn
ms|cik
```

There are also some lines with multiple terms in Malay that shouldn't be aliased to each other:

```
aras|tingkat|tkt
```

should be two separate lines:

```
aras
tingkat|tkt
```

Each line should only contain one word/phrase and any abbreviations for that specific phrase.

**Comment by Jeffrey04** [comment]
I fix it when i am back to work (don't have a local checkout here) Actually flat is also a Malay word lol

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 1, 2016 at 13:47, Al Barrentine<notifications@github.com> wrote:   
There are still a few more issues.

Lines like this:
flat|pangsapuri|rumah pangsa|p/puri

The word "flat" is still English should be removed and the other terms should be separated into distinct sets of abbreviations:
pangsapuri|p / puri
rumah pangsa

There are terms in personal_titles.txt that have English canonical forms like:
mr|encik|en
mrs|puan|pn
ms|cik

There are also some lines with multiple terms in Malay that shouldn't be aliased to each other:
aras|tingkat|tkt

should be two separate lines:
aras
tingkat|tkt

Each line should only contain one word/phrase and any abbreviations for that specific phrase.

**Comment by Jeffrey04** [comment]
a colleague of mine just reminded me about libpostal (he is particularly excited with the increased accuracy of the parser, making it usable for our work) and I found some of the changes I submitted here are dropped in the newer revision (and after being moved to new location). Just out of curiousity, are they redundant, or do you want me to compile a new pull request for this?

**Comment by albarrentine** [comment]
hey @Jeffrey04 - sorry, didn't mean to drop any changes! Must have lost this somewhere in the merge process. Yeah, if you have the branch still, can you resubmit in a new PR?

**Comment by Jeffrey04** [comment]
alright, let me compile a new one (:
congrats for the 1.0 release

**Pull request merged**
