### PR TITLE
Adding common UK County abbreviations

### PR DESCRIPTION
**Pull request by AeroXuk**
Adding common UK County abbreviations and some extra places. Sorted alphabetically.

### CODE REVIEW

**Comment by albarrentine** [comment]
So, had considered adding the UK abbreviations a while back, but decided against it. The main reason we include the US/CA abbreviations here is because they occur so frequently on state highways and in venue names that we needed them to be included.

It seems that in the UK the abbreviations are mostly used to abbreviate the counties themselves, but not as much in streets/venues. If that's the case, there's some upcoming work on automatic toponym resolution that should be able to encompass these abbreviations in a more principled way.

The primary issue with the expansion dictionaries is ambiguity. For instance, "Mx" may be an abbreviation for Middlesex but it's more commonly the country abbreviation for México (we also don't include ISO codes as part of expansion, so that can potentially get into weird situations like "Guadalajara, Middlesex") and might appear in venue names which also reference the toponym dictionary. "Hunts" could be "Huntingtonshire" but might also be someone's surname. "Beds" could just be the word "beds", etc.

As such, will have to either go through and add some of these to ambiguous_expansions.txt so the original terms are retained as well, or reserve the toponyms dictionary for street-level sorts of expansions and handle this piece under toponym resolution.

**Comment by AeroXuk** [comment]
Ok makes sense, some of the abbreviations are more ambiguous then others. If the set was reduced to remove some of the more ambiguous ones it would still be an improvement for UK counties.

Alternatively I don’t know what the complexity would be for this so please tell me if it’s not feasible. In a similar way that there are the state expansion files for various countries. Would it be possible to add expansions for other address components? People could then add country relative exansions for other address parts.

**Comment by albarrentine** [comment]
Hm, libpostal doesn't have a sense/knowledge of countries at this point. We do have a language classifier which is how libpostal knows which dictionaries to use for a given input without the user having to specify them.

With toponym resolution we'll be able to traverse the place hierarchy and provide possible country names, although only for full addresses that include things like city, state/province/region, etc. It would not work as well for simple street addresses i.e. it's unclear from "Bond Street" to which English-speaking country it's referring. Note: the resolution API can also match all the surface forms for a particular place ("Bedfordshire" and "Beds" would normalize to the same ID if they're consistent with the rest of the toponyms), so that might solve the problem in and of itself i.e. it's possible to normalize to a single display name and let the place DB do the work. But at the point where we can resolve to a place hierarchy for a given string, it's possible to obtain possible countries for a given string (that too can be ambiguous if e.g. just a city name is included and it could refer to multiple countries) and switch dictionaries as needed. Still in that case it might be wise to replicate anything country-specific in the language-only dictionaries as well for cases where there are no toponyms to identify the country.

**Comment by AeroXuk** [comment]
> It seems that in the UK the abbreviations are mostly used to abbreviate the counties themselves, but not as much in streets/venues. If that's the case, there's some upcoming work on automatic toponym resolution that should be able to encompass these abbreviations in a more principled way.

I'd agree, abbreviations within street names are usually just thinks like Rd/St/Ave etc.  If there is upcoming work on "automatic toponym resolution" it may be better to postpone this until then.

> As such, will have to either go through and add some of these to ambiguous_expansions.txt so the original terms are retained as well, or reserve the toponyms dictionary for street-level sorts of expansions and handle this piece under toponym resolution.

Ok, if the 3/4 character abbreviations are removed, leaving only the less ambiguous ones, should they still be in `toponyms.txt` or `ambiguous_expansions.txt`?

Are the files within `libpostal/resources/states/` just used for training the dataset or are they used for expansion? As these are in country coded files. I was thinking if something similar would be useful for other address levels.

> With toponym resolution we'll be able to traverse the place hierarchy and provide possible country codes, although only for full addresses that include things like city, state/province/region, etc.

Although not ready or implemented yet is there a prefered format or way we could contribute the information required for this? So that there is some data ready when it comes round to implementation, however far of that may or may not be?

**Comment by albarrentine** [comment]
Depends on the goal. Is it because the parser doesn't understand those abbreviations, or to ensure that they show up in expansions?

If it's the parser, then yes, there are some resources other than the dictionaries which are used to randomly abbreviate names in the training data, at which time we have lat/lons and can reverse geocode to country. In the runtime C library, we don't have that information available, just the text. We have a model to predict language, but country is a bit more tricky, as mentioned.

The idea for toponyms is to be able to resolve to an existing place hierarchy like GeoNames or [Who's On First](https://github.com/whosonfirst-data/whosonfirst-data) or some custom database of place names/IDs if it meets a few conditions, and as such all the name/language variations for different cities, regions, etc. come for free. Similarly, disambiguation can take context into account, so if "Beds" is encountered and conflicts with other toponyms in the string, it can be ignored. It can also follow some simple rules, so if "York" is encountered and it matches both the city of York and an abbreviation for "Yorkshire", the city of "York" would be preferred because it's a canonical match and it's a city rather than an admin.

I think I generally prefer this approach for most toponyms rather than trying to list them exhaustively in our dictionaries. Otherwise the expansions start to contain too many permutations.

**Comment by AeroXuk** [comment]
> Depends on the goal. Is it because the parser doesn't understand those abbreviations, or to ensure that they show up in expansions?

Abit of both, using Middlesex as the example, the abbreviation Middx is so common it is often used in postal databases; however the parser doesn't recognise it.  For address deduplication/matching, which is something I'm trying to do, having the expansions for the common abbreviations would be useful.

__Examples of parsing:__

Using `Middx`:
```
> 1 Church Street, Enfield, Middx, EN26AB
{ postcode no context|D, bias, word|D, first word|D, next word|church street, word+next word|D|church street }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield, prev tag+word|church street, prev tag+prev word|D }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield }
{ phrase|enfield, phrase type+phrase|suburb|enfield, phrase type+phrase|city|enfield, phrase type+phrase|city_district|enfield, commonly city_district|enfield, prev word|church street, prev word+word|church street|enfield, next word|UNKNOWN, word+next word|enfield|UNKNOWN, prev tag+word|enfield, prev tag+prev word|church street }
{ bias, word|ngrams|3|mid_, word|ngrams|3|_idd_, word|ngrams|3|_ddx, word|ngrams|4|midd_, word|ngrams|4|_iddx, prev word|enfield, prev word+word|enfield|UNKNOWN, next word|UNKNOWN_NUMERIC, word+next word|UNKNOWN|UNKNOWN_NUMERIC, prev tag+word|UNKNOWN, prev tag+prev word|enfield }
{ bias, prev word|UNKNOWN, prev word+word|UNKNOWN|UNKNOWN_NUMERIC, prev tag+word|UNKNOWN_NUMERIC, prev tag+prev word|UNKNOWN }

Result:

{
  "house_number": "1",
  "road": "church street",
  "city": "enfield",
  "house": "middx en26ab"
}
```

Using `Middlesex`:
```
> 1 Church Street, Enfield, Middlesex, EN26AB
{ postcode no context|D, bias, word|D, first word|D, next word|church street, word+next word|D|church street }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield, prev tag+word|church street, prev tag+prev word|D }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield }
{ phrase|enfield, phrase type+phrase|suburb|enfield, phrase type+phrase|city|enfield, phrase type+phrase|city_district|enfield, commonly city_district|enfield, prev word|church street, prev word+word|church street|enfield, next word|middlesex, word+next word|enfield|middlesex, prev tag+word|enfield, prev tag+prev word|church street }
{ phrase|middlesex, phrase type+phrase|suburb|middlesex, phrase type+phrase|city|middlesex, phrase type+phrase|state_district|middlesex, phrase type+phrase|state|middlesex, commonly state_district|middlesex, prev word|enfield, prev word+word|enfield|middlesex, next word|UNKNOWN_NUMERIC, word+next word|middlesex|UNKNOWN_NUMERIC, prev tag+word|middlesex, prev tag+prev word|enfield }
{ bias, prev word|middlesex, prev word+word|middlesex|UNKNOWN_NUMERIC, prev tag+word|UNKNOWN_NUMERIC, prev tag+prev word|middlesex }

Result:

{
  "house_number": "1",
  "road": "church street",
  "city": "enfield",
  "state": "middlesex",
  "postcode": "en26ab"
}
```

Also putting a space within the postcode (as is typical in the UK, last half always 3 characters, first half variable between 2 and 4) with Middx:
```
> 1 Church Street, Enfield, Middx, EN2 6AB
{ postcode no context|D, bias, word|D, first word|D, next word|church street, word+next word|D|church street }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield, prev tag+word|church street, prev tag+prev word|D }
{ phrase|church street, phrase type+phrase|suburb|church street, phrase type+phrase|city|church street, commonly city|church street, prev word|D, prev word+word|D|church street, next word|enfield, word+next word|church street|enfield }
{ phrase|enfield, phrase type+phrase|suburb|enfield, phrase type+phrase|city|enfield, phrase type+phrase|city_district|enfield, commonly city_district|enfield, prev word|church street, prev word+word|church street|enfield, next word|UNKNOWN, word+next word|enfield|UNKNOWN, prev tag+word|enfield, prev tag+prev word|church street }
{ bias, word|ngrams|3|mid_, word|ngrams|3|_idd_, word|ngrams|3|_ddx, word|ngrams|4|midd_, word|ngrams|4|_iddx, prev word|enfield, prev word+word|enfield|UNKNOWN, next word|enD, word+next word|UNKNOWN|enD, prev tag+word|UNKNOWN, prev tag+prev word|enfield }
{ postcode no context|enD, bias, word|enD, prev word|UNKNOWN, prev word+word|UNKNOWN|enD, prev tag+word|enD, prev tag+prev word|UNKNOWN }
{ postcode no context|Dab, bias, word|Dab, prev word|UNKNOWN, prev word+word|UNKNOWN|Dab }

Result:

{
  "house_number": "1",
  "road": "church street",
  "city": "enfield",
  "house": "middx",
  "road": "en2",
  "house_number": "6ab"
}
```

If there's a way I could contribute some extra rules for just the common county name abbreviations to the parser, how would I go about it?

**Comment by albarrentine** [comment]
So looking at this in OpenStreetMap, some of those names are just not getting added to the training data in the first place for various reasons. There are three types of counties listed in the abbreviations in this PR:

1. County names that are currently used and in OSM as `admin_level=6` (e.g. [Lancashire](http://www.openstreetmap.org/relation/88081), which already includes the abbreviation in OSM, and [Leicestershire](http://www.openstreetmap.org/relation/189890), which doesn't, so probably best to add `short_name` or `alt_name` to those records and we'll pick them up in the next batch).

2. Non-administrative counties, tagged in OSM as `boundary=ceremonial` counties. These were not included in our [field mappings](https://github.com/openvenues/libpostal/blob/918342d4c34c967550456dacfe7c2226ce932044/resources/boundaries/osm/gb.yaml), and, as far as I could tell when writing this, were not in current use. If that's not the case, those can be included, although it's slightly confusing why there's, for instance, both a [ceremonial county for Lancashire](https://www.openstreetmap.org/relation/118082) and an `admin_level=6` (current) county for ostensibly the same boundary.

3. Historic counties that are now part of Greater London, which are not included in OSM (like Middlesex). These also do not appear in any of the other data sets like GeoPlanet. Strangely, this shapefile of ceremonial county polygons from the British government also didn't include them: https://data.gov.uk/dataset/ceremonial-county-boundaries-of-england. Since they're not part of any of the place hierarchies we use, there's not much we can do on the libpostal side, so if having those names is important, you can either add the boundaries to OSM or if there's a free/open polygon data set that includes them, we can write a small module to reverse geocode UK entries to counties and add the abbreviations at training time for the v1.1 parser.

On the OSM side, you can view the ceremonial counties that exist in OSM [here](https://overpass-turbo.eu/?w=%22boundary%22%3D%22ceremonial%22+global&R). The best way to ensure those abbreviations are recognized in the parser is to add them to OSM as `short_name`, `alt_name`, etc. We reverse geocode to admin boundaries when constructing the parser training data, and pick different name tags at random. There's also a [config](https://github.com/openvenues/libpostal/blob/918342d4c34c967550456dacfe7c2226ce932044/resources/boundaries/names/global.yaml) that gives the probabilities that each name tag will be used, and allows for exceptions in case certain names should be ignored or used more often, etc.

Here's the OSM wiki page on English counties, that may have some info on how to map them: https://wiki.openstreetmap.org/wiki/English_Counties.

I've made a couple of UK-related improvements in the v1.1 branch for the next training (the ability to list locality + postal town on an address even though both are classified as `city` in libpostal, etc.) so can add the ceremonial counties to the list.

In any case, adding the abbreviations probably won't help with these cases since the core issue is in the underlying training examples, or lack thereof.

**Comment by philhutch50** [comment]
@AeroXuk Did you work out what to do with counties eventually?
Simple abbreviations like Northants - for Northamptonshire don't work either?

**Comment by AeroXuk** [comment]
@philhutch50 I made a change request to open street map to add the abbreviations that I had previously found and the change got rejected and they didn’t agree with all of them. I didn’t bother to try again. Maybe if they where all submitted as individual changes then some of them might have been accepted.

**Pull request closed without merging**
