### PR TITLE
#501. Fixed build issues on MSYS on Windows.

### PR DESCRIPTION
**Pull request by kyrill007**
This is a fix for build issues on windows.

### CODE REVIEW

**Comment by rauhs** [comment]
Just FYI: This does fix it for me in Windows. +1

**Comment by XtineInWa** [comment]
If this is fixed, how do I get my system upgraded with this fix? I'm still having problems after two weeks of trying.

**Comment by kyrill007** [comment]
you need to use the 64-bit version of msys2. Start the terminal with **mingw64.exe**.

**Comment by XtineInWa** [comment]
> you need to use the 64-bit version of msys2. Start the terminal with **mingw64.exe**.

thanks, I'll give it a try

**Pull request merged**
